trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals Windows-Machine

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.17.0'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: 'Installing the Packages'
  

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build'
  displayName: 'Bulding the code'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'mywebserver'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    addPipelineData: false
    addBaseImageData: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/my-app/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'