trigger:
- main
pool:
  name: default
  demands:
   - agent.name -equals LinuxMachine

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: 'Installing the Packages'
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build'
  displayName: 'Bulding the code'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'mywebserver'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'mywebserver'
    command: 'push'
    addPipelineData: false
    addBaseImageData: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/my-app/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'