trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals Windows-Machine

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: 'Installing the Packages'
  

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build'
  displayName: 'Bulding the code'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/my-app/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'