trigger:
- main
pool:
  name: Default
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.17.0'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: 'Installing the Packages'
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build'
  displayName: 'Bulding the code'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'mywebserver'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'mywebserver'
    command: 'push'
    addPipelineData: false
    addBaseImageData: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: 'Deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'